### ISSUE TITLE
invalid byte sequence in UTF-8 (ArgumentError) /w version 3.0.4

### ISSUE THREAD

**Issue by zenminimalist** [rccavalcanti/fyodor#8]
Thanks for adding the filename feature! I tried after updating to 3.0.4, but get the following error? Not sure, what this is related to. Any ideas?

`fyodor /Users/David/Downloads/My\ Clippings.txt /Users/David/Downloads
Using config at /Users/David/.config/fyodor/fyodor.toml.
/opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/parslet-2.0.0/lib/parslet/source/line_cache.rb:40:in `exist?': invalid byte sequence in UTF-8 (ArgumentError)
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/parslet-2.0.0/lib/parslet/source/line_cache.rb:40:in `scan_for_line_endings'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/parslet-2.0.0/lib/parslet/source.rb:25:in `initialize'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/parslet-2.0.0/lib/parslet/atoms/base.rb:29:in `new'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/parslet-2.0.0/lib/parslet/atoms/base.rb:29:in `parse'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/toml-0.3.0/lib/toml/parser.rb:9:in `initialize'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/toml-0.3.0/lib/toml.rb:23:in `new'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/toml-0.3.0/lib/toml.rb:23:in `load_file'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/fyodor-0.3.4/lib/fyodor/config_getter.rb:39:in `user_config'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/fyodor-0.3.4/lib/fyodor/config_getter.rb:15:in `config'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/fyodor-0.3.4/bin/fyodor:14:in `main'
	from /opt/homebrew/Cellar/gem-fyodor/0.3.4/gems/fyodor-0.3.4/bin/fyodor:70:in `<top (required)>'
	from /opt/homebrew/bin/fyodor:6:in `load'
	from /opt/homebrew/bin/fyodor:6:in `<main>'
	`

**Comment by zenminimalist** [comment]
I just managed to find the issue. I accidentally forgot one " from the output variable in the configuration file 🤦🏼‍♂️ With the correct config "Book Highlights - %{title} - %{author_fill}.md" it works just fine.
